token: ""

#Whitelist
useWhitelist: true
guildId: ""
permittedRoles:

#Alternate storage location for AuthProfiles
useAlternateLocation: false
#On Windows, use DOUBLE backslashes!. If you are using Windows Subsystem for Linux use /mnt/<DISK>/ instead of <DISK>:\\
alternateLocation: ""